import type { Guard, Site, Alert, PatrollingOfficer, Incident, SecurityAgency } from '@/types';

export const patrollingOfficers: PatrollingOfficer[] = [
  {
    id: 'PO01',
    name: 'Michael Scott',
    phone: '555-100-2000',
    email: 'michael.s@guardlink.com',
    avatar: 'https://placehold.co/100x100.png',
    assignedGuards: ['GL001', 'GL002', 'GL003'],
    routes: ['Downtown Route', 'Waterfront Route'],
  },
  {
    id: 'PO02',
    name: 'Jessica Pearson',
    phone: '555-100-2001',
    email: 'jessica.p@guardlink.com',
    avatar: 'https://placehold.co/100x100.png',
    assignedGuards: ['GL004', 'GL005', 'GL006'],
    routes: ['Tech Park Route', 'Cyberdyne Route'],
  },
  {
    id: 'PO03',
    name: 'Harvey Specter',
    phone: '555-100-2002',
    email: 'harvey.s@guardlink.com',
    avatar: 'https://placehold.co/100x100.png',
    assignedGuards: ['GL007', 'GL008'],
    routes: ['Industrial Zone Route'],
  },
];

export const incidents: Incident[] = [
    { id: 'INC001', date: '2024-07-20', type: 'Break-in', details: 'Attempted break-in at west entrance.', resolved: true},
    { id: 'INC002', date: '2024-07-21', type: 'Fire Alarm', details: 'False alarm triggered by dust.', resolved: true},
    { id: 'INC003', date: '2024-06-15', type: 'Vandalism', details: 'Graffiti on the north wall.', resolved: false},
    { id: 'INC004', date: '2024-05-10', type: 'Medical', details: 'Guard reported feeling unwell.', resolved: true},
    { id: 'INC005', date: '2024-04-01', type: 'Break-in', details: 'Successful break-in, items stolen.', resolved: false},
];


export const guards: Guard[] = [
  {
    id: 'GL001',
    name: 'John Doe',
    site: 'Downtown Mall',
    phone: '555-123-4567',
    location: 'Gate 4, Sector B',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 1,
    totalSelfieRequests: 20,
    patrollingOfficerId: 'PO01',
    performance: { perimeterAccuracy: 98, leaveDays: 2 },
  },
  {
    id: 'GL002',
    name: 'Jane Smith',
    site: 'Tech Park One',
    phone: '555-987-6543',
    location: 'Building A, Lobby',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 0,
    totalSelfieRequests: 25,
    patrollingOfficerId: 'PO01',
    performance: { perimeterAccuracy: 99, leaveDays: 0 },
  },
  {
    id: 'GL003',
    name: 'Mike Johnson',
    site: 'City Waterfront',
    phone: '555-555-1212',
    location: 'Pier 3, North End',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 8,
    totalSelfieRequests: 22,
    patrollingOfficerId: 'PO01',
    performance: { perimeterAccuracy: 92, leaveDays: 5 },
  },
  {
    id: 'GL004',
    name: 'Emily Williams',
    site: 'Tech Park One',
    phone: '555-333-4444',
    location: 'Building C, Entrance',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 0,
    totalSelfieRequests: 18,
    patrollingOfficerId: 'PO02',
    performance: { perimeterAccuracy: 100, leaveDays: 1 },
  },
  {
    id: 'GL005',
    name: 'Sarah Connor',
    site: 'Cyberdyne Systems',
    phone: '555-867-5309',
    location: 'R&D Dept',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 0,
    totalSelfieRequests: 10,
    patrollingOfficerId: 'PO02',
    performance: { perimeterAccuracy: 100, leaveDays: 0 },
  },
  {
    id: 'GL006',
    name: 'Kyle Reese',
    site: 'Cyberdyne Systems',
    phone: '555-867-5310',
    location: 'Mainframe Access',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 3,
    totalSelfieRequests: 15,
    patrollingOfficerId: 'PO02',
    performance: { perimeterAccuracy: 95, leaveDays: 3 },
  },
  {
    id: 'GL007',
    name: 'David Brown',
    site: 'Industrial Zone 5',
    phone: '555-111-2222',
    location: 'Warehouse 3',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 2,
    totalSelfieRequests: 30,
    patrollingOfficerId: 'PO03',
    performance: { perimeterAccuracy: 97, leaveDays: 1 },
  },
  {
    id: 'GL008',
    name: 'Chris Green',
    site: 'Industrial Zone 7',
    phone: '555-444-5555',
    location: 'Perimeter Fence West',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 5,
    totalSelfieRequests: 28,
    patrollingOfficerId: 'PO03',
    performance: { perimeterAccuracy: 94, leaveDays: 4 },
  },
];

export const securityAgencies: SecurityAgency[] = [
  {
    id: 'AGY01',
    name: 'GuardLink Security',
    phone: '555-001-0001',
    email: 'contact@guardlink.com',
    address: '123 Security Blvd, Safe City, CA, USA',
    avatar: 'https://placehold.co/100x100.png',
    city: 'Safe City',
    state: 'CA',
    country: 'USA',
  },
  {
    id: 'AGY02',
    name: 'Vigilant Watch',
    phone: '555-002-0002',
    email: 'info@vigilantwatch.com',
    address: '456 Protector Ave, Secure Town, WA, USA',
    avatar: 'https://placehold.co/100x100.png',
    city: 'Secure Town',
    state: 'WA',
    country: 'USA',
  },
  {
    id: 'AGY03',
    name: 'Aegis Protection',
    phone: '555-003-0003',
    email: 'support@aegispro.com',
    address: '789 Guardian Way, Metroplex, NY, USA',
    avatar: 'https://placehold.co/100x100.png',
    city: 'Metroplex',
    state: 'NY',
    country: 'USA',
  },
];

export const sites: Site[] = [
  {
    id: 'SITE01',
    name: 'Tech Park One',
    address: '123 Innovation Drive, Silicon Valley, CA',
    guards: ['GL002', 'GL004'],
    reportUrl: '#',
    coords: { x: 25, y: 30 },
    visited: true,
    towerco: 'TowerCo Alpha',
    incidents: [incidents[1]],
    assignedOn: '2024-05-10',
    agencyId: 'AGY01',
    geofencePerimeter: 500,
  },
  {
    id: 'SITE02',
    name: 'Downtown Mall',
    address: '456 Market Street, Metro City, NY',
    guards: ['GL001'],
    reportUrl: '#',
    coords: { x: 55, y: 45 },
    visited: false,
    towerco: 'TowerCo Beta',
    incidents: [incidents[0]],
    assignedOn: '2024-04-20',
    agencyId: 'AGY01',
    geofencePerimeter: 1000,
  },
  {
    id: 'SITE03',
    name: 'City Waterfront',
    address: '789 Ocean Avenue, Bay City, FL',
    guards: ['GL003'],
    reportUrl: '#',
    coords: { x: 75, y: 60 },
    visited: false,
    towerco: 'TowerCo Gamma',
    incidents: [],
    assignedOn: '2024-06-01',
    agencyId: 'AGY01',
    geofencePerimeter: 800,
  },
  {
    id: 'SITE04',
    name: 'Cyberdyne Systems',
    address: '2144 Kramer Street, Sunnyvale, CA',
    guards: ['GL005', 'GL006'],
    reportUrl: '#',
    coords: { x: 40, y: 70 },
    visited: true,
    towerco: 'TowerCo Alpha',
    incidents: [incidents[4]],
    agencyId: 'AGY02',
    geofencePerimeter: 1200,
  },
  {
    id: 'SITE05',
    name: 'Industrial Zone 5',
    address: '555 Factory Rd, Industry City, TX',
    guards: [],
    reportUrl: '#',
    coords: { x: 15, y: 80 },
    visited: false,
    towerco: 'TowerCo Delta',
    incidents: [],
    agencyId: 'AGY03',
    assignedOn: '2024-07-01',
    geofencePerimeter: 1500,
  },
  {
    id: 'SITE06',
    name: 'Industrial Zone 7',
    address: '777 Assembly Lane, Industry City, TX',
    guards: [],
    reportUrl: '#',
    coords: { x: 20, y: 85 },
    visited: true,
    towerco: 'TowerCo Delta',
    incidents: [],
    agencyId: 'AGY03',
    assignedOn: '2024-07-05',
    geofencePerimeter: 2000,
  },
  {
    id: 'SITE07',
    name: 'Metro Transit Hub',
    address: '101 Central Station, Metro City, NY',
    guards: [],
    reportUrl: '#',
    coords: { x: 60, y: 50 },
    visited: false,
    towerco: 'TowerCo Beta',
    incidents: [],
  },
  {
    id: 'SITE08',
    name: 'North Point Relay',
    address: '555 Summit Rd, Alpine, CA',
    guards: [],
    reportUrl: '#',
    coords: { x: 30, y: 15 },
    visited: false,
    towerco: 'TowerCo Alpha',
    incidents: [],
  },
  {
    id: 'SITE09',
    name: 'East Valley Repeater',
    address: '800 Valley View, Sunrise, CA',
    guards: [],
    reportUrl: '#',
    coords: { x: 45, y: 25 },
    visited: false,
    towerco: 'TowerCo Alpha',
    incidents: [],
  },
];

export const alerts: Alert[] = [
  // 2024 Data
  // Jan
  { id: 'A240101', type: 'Emergency', date: '2024-01-15 10:00', site: 'Tech Park One', guard: 'Jane Smith', status: 'Resolved', callDetails: 'Power outage in Building B.', images: ['https://placehold.co/600x400.png']},
  // Feb
  { id: 'A240201', type: 'Emergency', date: '2024-02-10 18:30', site: 'Downtown Mall', guard: 'John Doe', status: 'Resolved', callDetails: 'Suspicious person reported near the food court.' },
  { id: 'A240202', type: 'Missed Selfie', date: '2024-02-20 09:00', site: 'City Waterfront', guard: 'Mike Johnson', status: 'Resolved'},
  // Mar
  { id: 'A240301', type: 'Emergency', date: '2024-03-05 21:00', site: 'Cyberdyne Systems', guard: 'Sarah Connor', status: 'Resolved', callDetails: 'Unauthorized access attempt at main gate.', images: ['https://placehold.co/600x400.png'] },
  { id: 'A240302', type: 'Emergency', date: '2024-03-25 14:00', site: 'Industrial Zone 5', guard: 'David Brown', status: 'Investigating', callDetails: 'Fence breach detected on the western perimeter.' },
  // Apr
  { id: 'A240401', type: 'Emergency', date: '2024-04-01 11:20', site: 'Cyberdyne Systems', guard: 'Kyle Reese', status: 'Resolved', callDetails: 'Medical emergency, employee fainted.', images: ['https://placehold.co/600x400.png'] },
  // May
  { id: 'A240501', type: 'Emergency', date: '2024-05-12 03:00', site: 'Downtown Mall', guard: 'John Doe', status: 'Resolved', callDetails: 'Shoplifting incident at a retail store.' },
  { id: 'A240502', type: 'Guard Out of Premises', date: '2024-05-22 16:00', site: 'Industrial Zone 7', guard: 'Chris Green', status: 'Resolved'},
  // Jun
  { id: 'A240601', type: 'Emergency', date: '2024-06-18 17:45', site: 'Tech Park One', guard: 'Emily Williams', status: 'Resolved', callDetails: 'Minor traffic accident in the parking lot.', images: ['https://placehold.co/600x400.png']},
  // Jul
  {
    id: 'A001',
    type: 'Emergency',
    date: '2024-07-20 14:30',
    site: 'Downtown Mall',
    guard: 'John Doe',
    status: 'Active',
    callDetails:
      'This is John Doe at Downtown Mall, Gate 4. We have a potential break-in situation at the west entrance near the electronics store. Requesting immediate backup. I see two individuals acting suspiciously. The time is approximately 2:30 PM.',
    images: ['https://placehold.co/600x400.png', 'https://placehold.co/600x400.png'],
  },
  {
    id: 'A005',
    type: 'Emergency',
    date: '2024-07-21 02:14',
    site: 'Cyberdyne Systems',
    guard: 'Sarah Connor',
    status: 'Active',
    callDetails:
      'Fire alarm activated on the third floor, R&D department. I am proceeding to the location to investigate. All personnel are being evacuated. Time is 2:14 AM. No smoke visible yet.',
    images: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'A006',
    type: 'Emergency',
    date: '2024-07-19 10:00',
    site: 'Tech Park One',
    guard: 'Jane Smith',
    status: 'Resolved',
    callDetails: 'False alarm at Building A. A smoke detector was triggered by dust from construction work nearby. Situation is normal. The time is 10:00 AM.',
    images: ['https://placehold.co/600x400.png'],
  },
  {
    id: 'A002',
    type: 'Missed Selfie',
    date: '2024-07-20 08:05',
    site: 'City Waterfront',
    guard: 'Mike Johnson',
    status: 'Investigating',
  },
  {
    id: 'A003',
    type: 'Guard Out of Premises',
    date: '2024-07-19 22:00',
    site: 'Tech Park One',
    guard: 'Jane Smith',
    status: 'Resolved',
  },
  {
    id: 'A004',
    type: 'Missed Selfie',
    date: '2024-07-18 16:00',
    site: 'City Waterfront',
    guard: 'Mike Johnson',
    status: 'Resolved',
  },

  // 2023 Data
  { id: 'A230801', type: 'Emergency', date: '2023-08-01 12:00', site: 'Downtown Mall', guard: 'John Doe', status: 'Resolved', callDetails: 'Lost child reported, found safe.'},
  { id: 'A231001', type: 'Emergency', date: '2023-10-15 19:00', site: 'Tech Park One', guard: 'Jane Smith', status: 'Resolved', callDetails: 'Car alarm going off in parking garage.' },
  { id: 'A231101', type: 'Emergency', date: '2023-11-20 16:30', site: 'City Waterfront', guard: 'Mike Johnson', status: 'Resolved', callDetails: 'Public disturbance on the pier.' },
];
