
import type { Guard, Site, Incident, PatrollingOfficer, SecurityAgency } from '@/types';

export const patrollingOfficers: PatrollingOfficer[] = [
  {
    id: 'PO01',
    name: 'Michael Scott',
    phone: '555-100-2000',
    email: 'michael.s@guardlink.com',
    avatar: 'https://placehold.co/100x100.png',
    routes: ['Downtown Route', 'Waterfront Route'],
    averageResponseTime: 15,
  },
  {
    id: 'PO02',
    name: 'Jessica Pearson',
    phone: '555-100-2001',
    email: 'jessica.p@guardlink.com',
    avatar: 'https://placehold.co/100x100.png',
    routes: ['Tech Park Route', 'Cyberdyne Route'],
    averageResponseTime: 12,
  },
  {
    id: 'PO03',
    name: 'Harvey Specter',
    phone: '555-100-2002',
    email: 'harvey.s@guardlink.com',
    avatar: 'https://placehold.co/100x100.png',
    routes: ['Industrial Zone Route'],
    averageResponseTime: 18,
  },
];

export const incidents: Incident[] = [
    { id: 'INC001', date: '2024-07-20', type: 'Break-in', details: 'Attempted break-in at west entrance.', status: 'Active', guard: 'John Doe', site: 'Downtown Mall', images: ['https://placehold.co/600x400.png']},
    { id: 'INC002', date: '2024-07-21', type: 'Fire Alarm', details: 'False alarm triggered by dust.', status: 'Resolved', guard: 'Jane Smith', site: 'Tech Park One'},
    { id: 'INC003', date: '2024-06-15', type: 'Vandalism', details: 'Graffiti on the north wall.', status: 'Under Review', guard: 'Mike Johnson', site: 'City Waterfront'},
    { id: 'INC004', date: '2024-05-10', type: 'Medical', details: 'Guard reported feeling unwell.', status: 'Resolved', guard: 'Sarah Connor', site: 'Cyberdyne Systems'},
    { id: 'INC005', date: '2024-04-01', type: 'Break-in', details: 'Successful break-in, items stolen.', status: 'Resolved', guard: 'Kyle Reese', site: 'Cyberdyne Systems'},
];


export const guards: Guard[] = [
  {
    id: 'GL001',
    name: 'John Doe',
    site: 'Downtown Mall',
    phone: '555-123-4567',
    location: 'Gate 4, Sector B',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 1,
    totalSelfieRequests: 20,
    performance: { perimeterAccuracy: 98, leaveDays: 2 },
    patrollingOfficerId: 'PO01',
  },
  {
    id: 'GL002',
    name: 'Jane Smith',
    site: 'Tech Park One',
    phone: '555-987-6543',
    location: 'Building A, Lobby',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 0,
    totalSelfieRequests: 25,
    performance: { perimeterAccuracy: 99, leaveDays: 0 },
    patrollingOfficerId: 'PO02',
  },
  {
    id: 'GL003',
    name: 'Mike Johnson',
    site: 'City Waterfront',
    phone: '555-555-1212',
    location: 'Pier 3, North End',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 8,
    totalSelfieRequests: 22,
    performance: { perimeterAccuracy: 92, leaveDays: 5 },
    patrollingOfficerId: 'PO01',
  },
  {
    id: 'GL004',
    name: 'Emily Williams',
    site: 'Tech Park One',
    phone: '555-333-4444',
    location: 'Building C, Entrance',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 0,
    totalSelfieRequests: 18,
    performance: { perimeterAccuracy: 100, leaveDays: 1 },
    patrollingOfficerId: 'PO02',
  },
  {
    id: 'GL005',
    name: 'Sarah Connor',
    site: 'Cyberdyne Systems',
    phone: '555-867-5309',
    location: 'R&D Dept',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 0,
    totalSelfieRequests: 10,
    performance: { perimeterAccuracy: 100, leaveDays: 0 },
    patrollingOfficerId: 'PO02',
  },
  {
    id: 'GL006',
    name: 'Kyle Reese',
    site: 'Cyberdyne Systems',
    phone: '555-867-5310',
    location: 'Mainframe Access',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 3,
    totalSelfieRequests: 15,
    performance: { perimeterAccuracy: 95, leaveDays: 3 },
    patrollingOfficerId: 'PO02',
  },
  {
    id: 'GL007',
    name: 'David Brown',
    site: 'Industrial Zone 5',
    phone: '555-111-2222',
    location: 'Warehouse 3',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 2,
    totalSelfieRequests: 30,
    performance: { perimeterAccuracy: 97, leaveDays: 1 },
    patrollingOfficerId: 'PO03',
  },
  {
    id: 'GL008',
    name: 'Chris Green',
    site: 'Industrial Zone 7',
    phone: '555-444-5555',
    location: 'Perimeter Fence West',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 5,
    totalSelfieRequests: 28,
    performance: { perimeterAccuracy: 94, leaveDays: 4 },
  },
  {
    id: 'GL009',
    name: 'Alex Ray',
    site: 'North Point Relay',
    phone: '555-222-3333',
    location: 'Main Tower',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 1,
    totalSelfieRequests: 15,
    performance: { perimeterAccuracy: 99, leaveDays: 0 },
  },
  {
    id: 'GL010',
    name: 'Maria Garcia',
    site: 'East Valley Repeater',
    phone: '555-666-7777',
    location: 'Substation A',
    avatar: 'https://placehold.co/100x100.png',
    missedSelfieCount: 0,
    totalSelfieRequests: 20,
    performance: { perimeterAccuracy: 100, leaveDays: 2 },
  },
];

export const securityAgencies: SecurityAgency[] = [
  {
    id: 'AGY01',
    name: 'GuardLink Security',
    phone: '555-001-0001',
    email: 'contact@guardlink.com',
    address: '123 Security Blvd, Safe City, CA, USA',
    avatar: 'https://placehold.co/100x100.png',
    city: 'Safe City',
    state: 'CA',
    country: 'USA',
  },
  {
    id: 'AGY02',
    name: 'Vigilant Watch',
    phone: '555-002-0002',
    email: 'info@vigilantwatch.com',
    address: '456 Protector Ave, Secure Town, WA, USA',
    avatar: 'https://placehold.co/100x100.png',
    city: 'Secure Town',
    state: 'WA',
    country: 'USA',
  },
  {
    id: 'AGY03',
    name: 'Aegis Protection',
    phone: '555-003-0003',
    email: 'support@aegispro.com',
    address: '789 Guardian Way, Metroplex, NY, USA',
    avatar: 'https://placehold.co/100x100.png',
    city: 'Metroplex',
    state: 'NY',
    country: 'USA',
  },
];

export const sites: Site[] = [
  {
    id: 'SITE01',
    name: 'Tech Park One',
    address: '123 Innovation Drive, Silicon Valley, CA',
    city: 'Silicon Valley',
    state: 'CA',
    country: 'USA',
    guards: ['GL002', 'GL004'],
    reportUrl: '#',
    coords: { x: 25, y: 30 },
    visited: true,
    towerco: 'TowerCo Alpha',
    assignedOn: '2024-05-10',
    agencyId: 'AGY01',
    patrollingOfficerId: 'PO02',
    geofencePerimeter: 500,
  },
  {
    id: 'SITE02',
    name: 'Downtown Mall',
    address: '456 Market Street, Metro City, NY',
    city: 'Metro City',
    state: 'NY',
    country: 'USA',
    guards: ['GL001'],
    reportUrl: '#',
    coords: { x: 55, y: 45 },
    visited: false,
    towerco: 'TowerCo Beta',
    assignedOn: '2024-04-20',
    agencyId: 'AGY01',
    patrollingOfficerId: 'PO01',
    geofencePerimeter: 1000,
  },
  {
    id: 'SITE03',
    name: 'City Waterfront',
    address: '789 Ocean Avenue, Bay City, FL',
    city: 'Bay City',
    state: 'FL',
    country: 'USA',
    guards: ['GL003'],
    reportUrl: '#',
    coords: { x: 75, y: 60 },
    visited: false,
    towerco: 'TowerCo Gamma',
    assignedOn: '2024-06-01',
    agencyId: 'AGY01',
    patrollingOfficerId: 'PO01',
    geofencePerimeter: 800,
  },
  {
    id: 'SITE04',
    name: 'Cyberdyne Systems',
    address: '2144 Kramer Street, Sunnyvale, CA',
    city: 'Sunnyvale',
    state: 'CA',
    country: 'USA',
    guards: ['GL005', 'GL006'],
    reportUrl: '#',
    coords: { x: 40, y: 70 },
    visited: true,
    towerco: 'TowerCo Alpha',
    agencyId: 'AGY02',
    patrollingOfficerId: 'PO02',
    geofencePerimeter: 1200,
    assignedOn: '2024-03-15',
  },
  {
    id: 'SITE05',
    name: 'Industrial Zone 5',
    address: '555 Factory Rd, Industry City, TX',
    city: 'Industry City',
    state: 'TX',
    country: 'USA',
    guards: [],
    reportUrl: '#',
    coords: { x: 15, y: 80 },
    visited: false,
    towerco: 'TowerCo Delta',
    agencyId: 'AGY03',
    patrollingOfficerId: 'PO03',
    assignedOn: '2024-07-01',
    geofencePerimeter: 1500,
  },
  {
    id: 'SITE06',
    name: 'Industrial Zone 7',
    address: '777 Assembly Lane, Industry City, TX',
    city: 'Industry City',
    state: 'TX',
    country: 'USA',
    guards: [],
    reportUrl: '#',
    coords: { x: 20, y: 85 },
    visited: true,
    towerco: 'TowerCo Delta',
    agencyId: 'AGY03',
    patrollingOfficerId: 'PO03',
    assignedOn: '2024-07-05',
    geofencePerimeter: 2000,
  },
  {
    id: 'SITE07',
    name: 'Metro Transit Hub',
    address: '101 Central Station, Metro City, NY',
    city: 'Metro City',
    state: 'NY',
    country: 'USA',
    guards: [],
    reportUrl: '#',
    coords: { x: 60, y: 50 },
    visited: false,
    towerco: 'TowerCo Beta',
    agencyId: 'AGY01',
    patrollingOfficerId: 'PO01',
    assignedOn: '2024-05-20',
  },
  {
    id: 'SITE08',
    name: 'North Point Relay',
    address: '555 Summit Rd, Alpine, CA',
    city: 'Alpine',
    state: 'CA',
    country: 'USA',
    guards: ['GL009'],
    reportUrl: '#',
    coords: { x: 30, y: 15 },
    visited: false,
    towerco: 'TowerCo Alpha',
    agencyId: 'AGY01',
    assignedOn: '2024-06-10',
  },
  {
    id: 'SITE09',
    name: 'East Valley Repeater',
    address: '800 Valley View, Sunrise, CA',
    city: 'Sunrise',
    state: 'CA',
    country: 'USA',
    guards: ['GL010'],
    reportUrl: '#',
    coords: { x: 45, y: 25 },
    visited: false,
    towerco: 'TowerCo Alpha',
    agencyId: 'AGY01',
    assignedOn: '2024-06-11',
  },
  {
    id: 'SITE10',
    name: 'South Ridge Tower',
    address: '900 Ridge Line, Crestwood, CA',
    city: 'Crestwood',
    state: 'CA',
    country: 'USA',
    guards: [],
    reportUrl: '#',
    coords: { x: 35, y: 35 },
    visited: false,
    towerco: 'TowerCo Alpha',
    agencyId: 'AGY01',
    assignedOn: '2024-06-12',
  },
  {
    id: 'SITE11',
    name: 'West Ridge Antenna',
    address: '110 Ridge Line, Crestwood, CA',
    city: 'Crestwood',
    state: 'CA',
    country: 'USA',
    guards: [],
    reportUrl: '#',
    coords: { x: 25, y: 40 },
    visited: false,
    towerco: 'TowerCo Alpha',
  },
  {
    id: 'SITE12',
    name: 'Central Valley Hub',
    address: '220 Valley Center, Sunrise, CA',
    city: 'Sunrise',
    state: 'CA',
    country: 'USA',
    guards: [],
    reportUrl: '#',
    coords: { x: 50, y: 30 },
    visited: false,
    towerco: 'TowerCo Alpha',
  },
];
